### ISSUE TITLE
General inquiry

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [rliang/gnome-shell-extension-tilingnome#11]
I'm just confused a bit....what exactly is the Master Count?

And one more question. How do I change the vertical split of two windows in a horisontal layout?  
...or the horisontal split in a vertical layout  
![Screenshot from 2019-05-31 09-40-08](https://user-images.githubusercontent.com/17408117/58693221-35a04e80-8388-11e9-9e23-bff9cf69afcd.png)

So to reference the screenshot from above, how do I make the browser window taller?

**Comment by rliang** [comment]
This is based on DWM and Awesome's horizontal and vertical layouts.

In both, there is a "master area", which contains a main window (or many, set by the master count).
The non-master windows occupy the rest of the screen.

By design, you can't change the vertical split in a horizontal layout, or vice-versa.
